config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'pages/home'
root 'pages#home'

get 'about' => 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'PINTEREST' ,root_path ,class:'navbar-brand'%>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to "Inicio" ,root_path %></li>
        <li><%=link_to "Nosotros",about_path %></li>
        <%if user_signed_in? %>
          <li> <%=link_to 'configurar cuenta',edit_user_registration_path %></li>
          <li><%= link_to  'Finalizar sesion',destroy_user_session_path , method: :delete%></li>
          <%else%>
          <li><%= link_to  'Iniciar sesion',new_user_session_path%></li>
          <%end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiFirtappRor</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </head>
  <body>
    <%=render 'layouts/header'%>
    <div class="container">
      <% flash.each do|name , msg|%>
        <%= content_tag(:div,msg,class: "alert alert-info") %>
      <%end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Acerca de nosotros </h1>
<p>Estamos trabajando en la aplicaciond de Pinteres para rails </p>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Bienvenido a mi Aplicacion </h1>
  <%if user_signed_in? %>
  #hacer alg
  <% else %>
<p>
<%= link_to "Registrate" , new_user_registration_path , class:'btn btn-primary btn-lg'%>
 </p>
 <% end %>
</div>